# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f65a0d333de8c2b31dba592c15423b514238112d3655308ef9dcb9324cf1c9ceed82517fcb48dacb5f14fc059a823767807afff8b71e8813447b67bbf851e4ff

test:
  secret_key_base: 96253ec1b914db8046992322c96e751fbcfaee5ef895040331918286fd898a055f3bc404779eb58524f5793b71bf0ec7108c578f892f0937e347bbd6485c2f5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
